### ISSUE TITLE
UI scales when toggling theme

### ISSUE THREAD

**Issue by yunkhngn** [rdbende/Sun-Valley-ttk-theme#11] opened 2021-12-10 03:35 UTC
I'm using Python and Tkinter for GUI. I've a function using switch and ttk for switching between light and dark mode:

```
def ThemeChanger():
    if screen.tk.call("ttk::style", "theme", "use") == "sun-valley-dark":
        # Set light theme
        screen.tk.call("set_theme", "light")
    else:
        # Set dark theme
        screen.tk.call("set_theme", "dark"
```
But when I clicked into the switch, all the UI automatically scales a litter bit:

![image](https://user-images.githubusercontent.com/44545000/145512965-7a857763-8bf2-4d8b-abba-1a3a91b6b2af.png)

![image](https://user-images.githubusercontent.com/44545000/145512978-1932b59c-02e8-40c1-a983-f73f741c8c9d.png)

It will scale larger if i use tabs or table in ttk Tkinter, and won't scale back when switch to light mode, it scales more and more when I clicked into theme switch button:

```
def change_theme():
    # NOTE: The theme's real name is sun-valley-<mode>
    if root.tk.call("ttk::style", "theme", "use") == "sun-valley-dark":
        # Set light theme
        root.tk.call("set_theme", "light")
    else:
        # Set dark theme
        root.tk.call("set_theme", "dark")
```
![image](https://user-images.githubusercontent.com/44545000/145513015-28597932-2519-4f68-8b4f-962ff6434941.png)
![image](https://user-images.githubusercontent.com/44545000/145513028-22f26644-2180-4a88-bbe3-bc02f92fbd3a.png)
![image](https://user-images.githubusercontent.com/44545000/145513032-b753f675-1284-4989-8bf6-866f62d584be.png)
![image](https://user-images.githubusercontent.com/44545000/145513036-9b86904b-d2d8-4ca8-95ee-9cfc09abca6d.png)
![image](https://user-images.githubusercontent.com/44545000/145513042-f2243ae4-f44f-4e05-9b44-27dab47141d1.png)

I don't know how to fix this. I would so appreciate if anyone can recommend me improving these. Thank you!

**Comment by rdbende** [comment] 2021-12-10 16:21
Duplicate of #6 
I just quickly done a `diff light.tcl dark.tcl` and I found nothing that might cause this issue. I remember I saw this issue with other ttk themes, but it's strange that it scales back when changing back to light theme.

**Comment by rdbende** [comment] 2022-06-21 15:46
Probably related to rdbende/Azure-ttk-theme#20

**Comment by rdbende** [comment] 2022-07-19 08:52
From the README:
>When you change the theme, and your app has a treeview, the window resizes. This is a quite strange bug that applies to other ttk themes too.

**Comment by rdbende** [comment] 2022-08-15 16:48
> Probably related to https://github.com/rdbende/Azure-ttk-theme/issues/20

Not related to it. This is a bug in Tk itself. rdbende/Azure-ttk-theme#40

**Comment by rdbende** [comment] 2022-08-15 19:02
Bug reported in Tk core: https://core.tcl-lang.org/tk/tktview?name=bc602049ab

**Closed** 2022-09-11 10:57 UTC
